### ISSUE TITLE
Can you provide a full exemple without Kotlin?

### ISSUE THREAD

**Issue by PedroBarbosaPT** [porokoro/paperboy#3]
Title says it all.
Thanks

**Comment by porokoro** [comment]
Hello @PedroBarbosaPT, I'm sorry for the late reply. First of all thank you for the interest in my library.

At the moment there are two dedicated java files ([link](https://github.com/porokoro/paperboy/tree/develop/sample/src/main/java/com/github/porokoro/paperboy/sample)) that show how to invoke Paperboy from Java.

Would this be sufficient for you? 

All you have to do is, taking the `Fragment` that is created by `PaperboyChainBuilder` and `PaperboyBuilderKt.buildPaperboy` and put it in some container via the `FragmentManager` as you would do with every other Fragment.

Something like this (in case you would use the Java classes of the sample app):
```java
public class SampleActivity extends AppCompatActivity {
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        if (savedInstanceState == null)
            getFragmentManager().beginTransaction()
                    .replace(R.id.content, JavaSample2.buildCustom())
                    .commit();
    }
}
```

**Comment by PedroBarbosaPT** [comment]
Thanks for the help, but I still have 1 error.

`buildCustom (Context) in SampleActivity cannot be applied to ()`

So I did this:

        Context context = this.getApplicationContext();
        if (savedInstanceState == null)
            getFragmentManager().beginTransaction()
                    .replace(R.id.content, changeLog.buildCustom(context))
                    .commit();
    }

And now:

> Wrong 2nd argument type. Found: 'com.github.porokoro.paperboy.PaperboyFragment', required: 'android.app.Fragment'

Thanks for all the help so far

**Comment by porokoro** [comment]
My bad, it should be `getSupportFragmentManager()` instead of `getFragmentManager()`.

**Comment by PedroBarbosaPT** [comment]
Thanks, its now working like a charm 👍 ;)

One more thing please
Can you provide me this layout? https://raw.githubusercontent.com/porokoro/paperboy/develop/art/screenshot-2.png

**Comment by porokoro** [comment]
For this layout all you have to do is setting the view type to `LABEL`.

```java
new PaperboyChainBuilder(context)
                .viewType(ViewTypes.LABEL)
                .buildFragment();
```

Then you can throw the returned fragment into the SupportFragmentManager as usual.

**Comment by PedroBarbosaPT** [comment]
Thanks
Great job / Great Design 👍
